Repository nodeshift-starters/nodejs-circuit-breaker, pull requests merged in 2018-02, with the labels that each got.

#33 fix: issue with mac bash specific command
  .gitignore
  start-localhost.sh
Labels: blocked

#34 feat(package): Move nsp check from prepare step to an optional script.
  greeting-service/licenses/licenses.xml
  greeting-service/package-lock.json
  greeting-service/package.json
  name-service/licenses/licenses.xml
  name-service/package-lock.json
  name-service/package.json
Labels: in progress, review

#35 feat(script): script for standard-version-release
  greeting-service/package-lock.json
  greeting-service/package.json
  name-service/package-lock.json
  name-service/package.json
  standard-version-release-dry-run.sh
  standard-version-release.sh
Labels: review

#37 chore(package): update nodeshift to 1.4.0
  greeting-service/package-lock.json
  greeting-service/package.json
  name-service/package-lock.json
  name-service/package.json
Labels: in progress, review
